name: Flutter Build APK

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: 🔐 Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/ztech.jks

      - name: 🔐 Create key.properties
        run: |
          cat <<KEY > android/key.properties
          storePassword=ztech212321
          keyPassword=ztech212321
          keyAlias=ztech
          storeFile=ztech.jks
          KEY

      - name: Build APK Release
        run: flutter build apk --release

      - name: 📦 Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
